image: jekyll/builder:latest  # Includes Ruby, Jekyll, Bundler

stages:
  - setup
  - build
  - deploy

variables:
  JEKYLL_ENV: production  # Set Jekyll to production mode

cache:
  paths:
    - venv/  # Cache Python virtual environment
    - .bundle/  # Cache Jekyll dependencies
    - vendor/bundle  # Cache Ruby gems

setup:
  stage: setup
  script:
    - python3 -m venv venv  # Create virtual environment
    - source venv/bin/activate  # Activate venv
    - pip install --upgrade pip  # Upgrade pip
    - pip install -r requirements.txt  # Install Python dependencies
    - gem install bundler  # Ensure Bundler is installed for Ruby
  artifacts:
    paths:
      - venv/  # Save virtual environment for next stages

build:
  stage: build
  dependencies:
    - setup  # Ensure setup stage runs first
  script:
    - source venv/bin/activate  # Reactivate virtual environment
    - bundle install  # Install Jekyll & dependencies
    - jekyll build  # Build Jekyll site
  artifacts:
    paths:
      - _site/  # Store the built site

deploy:
  stage: deploy
  script:
    - cp -r _site/* public/  # Copy built site to public directory for GitLab Pages
  artifacts:
    paths:
      - public/  # GitLab Pages expects files in the "public/" directory
  only:
    - main  # Deploy only on the main branch
