source "https://rubygems.org"

gem "jekyll", "~> 3.10"
gem "jekyll-github-metadata"
gem "jekyll-seo-tag"
gem "jekyll-coffeescript"
gem "jekyll-commonmark-ghpages"
gem "jekyll-paginate"
gem "jekyll-relative-links"
gem "jekyll-optional-front-matter"
gem "jekyll-readme-index"
gem "jekyll-default-layout"
gem "jekyll-titles-from-headings"
